import React,{useEffect,useState,useRef,useCallback} from './react';
import type {Session,State,Meta,Command,ExportResult} from './types';
import {api,openSession,projectPath} from './api';
import {human,displayTitle} from './utils';
import {Icon,Modal,ErrorNotice,Empty,ContextView,ExportLinks} from './components/Primitives';
import {ActionDialog} from './components/ActionDialog';
import {Inspector} from './components/Inspector';
import {Canvas} from './canvas/Canvas';
import {WorkspacePage,OverviewPage,IntakePage,LibraryPage,OutlinePage,GuidePage,EditorPage,FramesPage,CompositionPage,SettingsPage,AutomationPage} from './pages/Pages';
const NAV=[['overview','Project overview','home'],['intake','Image intake','inbox'],['library','Reference library','library'],['outline','Story outline','outline'],['guide','Story guide','guide'],['editor','Scene & shot editor','edit'],['canvas','Story canvas','graph'],['frames','Storyboard frames','frames'],['composition','Board & exports','export'],['automation','Image tools','automation'],['settings','Project care','settings']];
interface WriteRefreshWarning{projectId:string;message:string}
export function App(){
 const [session,setSession]=useState<Session|null>(null),[meta,setMeta]=useState<Meta|null>(null),[state,setState]=useState<State|null>(null);
 const [page,setPage]=useState(location.hash.slice(1)||'workspace'),[selected,setSelected]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [dialog,setDialog]=useState<{command:Command;defaults:Record<string,any>}|null>(null),[resultModal,setResultModal]=useState<{title:string;data:any}|null>(null),[result,setResult]=useState<ExportResult|null>(null),[palette,setPalette]=useState(false),[paletteQuery,setPaletteQuery]=useState(''),[toast,setToast]=useState(''),[mobileNav,setMobileNav]=useState(false),[changed,setChanged]=useState(false),[writeRefreshError,setWriteRefreshError]=useState<WriteRefreshWarning|null>(null);
 const navRef=useRef<HTMLElement|null>(null),mobileNavOpener=useRef<HTMLElement|null>(null),mobileNavWasOpen=useRef(false);
 useEffect(()=>{const media=window.matchMedia('(max-width:800px)');const update=()=>{if(navRef.current)navRef.current.inert=media.matches&&!mobileNav;};update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[mobileNav]);
 useEffect(()=>{if(mobileNav){mobileNavWasOpen.current=true;const first=navRef.current?.querySelector<HTMLElement>('button:not(:disabled)');first?.focus();return;}if(mobileNavWasOpen.current){mobileNavWasOpen.current=false;const opener=mobileNavOpener.current;mobileNavOpener.current=null;if(opener?.isConnected&&!opener.matches(':disabled')&&!opener.closest('[inert]')&&opener.getClientRects().length>0)opener.focus({preventScroll:true});}},[mobileNav]);
 const stateRef=useRef<State|null>(null);stateRef.current=state;const dialogRef=useRef(dialog);dialogRef.current=dialog;
 const pageRef=useRef(page);pageRef.current=page;const canvasNavigationGuard=useRef<((commit:()=>void)=>boolean)|null>(null);
 const registerCanvasNavigationGuard=useCallback((guard:(commit:()=>void)=>boolean)=>{canvasNavigationGuard.current=guard;return()=>{if(canvasNavigationGuard.current===guard)canvasNavigationGuard.current=null;}},[]);
 function notify(message:string){setToast(message);}
 function commitNavigation(next:string){if(next!==pageRef.current){if(location.hash!==`#${next}`)location.hash=next;pageRef.current=next;setPage(next);}setMobileNav(false);}
 function go(next:string){if(next===pageRef.current){setMobileNav(false);return;}const commit=()=>commitNavigation(next);const guard=canvasNavigationGuard.current;if(guard&&!guard(commit)){setMobileNav(false);return;}commit();}
 async function load(id:string){const next=await api<State>(projectPath(id,'/state'));setState(next);setChanged(false);return next;}
 async function refresh(){const id=stateRef.current?.project.id;if(!id)throw new Error('Open a project first.');const next=await load(id);setWriteRefreshError(current=>current?.projectId===id?null:current);return next;}
 async function refreshSession(){const s=await openSession();setSession(s);setMeta(await api<Meta>('/meta'));}
 async function open(id:string){setError('');setLoading(true);try{await api('/active','POST',{id});const previousId=stateRef.current?.project.id;await load(id);if(previousId!==id)setWriteRefreshError(null);setSelected(null);setResult(null);await refreshSession();go('overview');}catch(e:any){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{let alive=true;(async()=>{try{const s=await openSession();const m=await api<Meta>('/meta');if(!alive)return;setSession(s);setMeta(m);if(s.active_project_id)await load(s.active_project_id);else go('workspace');}catch(e:any){setError(e.message);}finally{if(alive)setLoading(false);}})();const h=()=>{const next=location.hash.slice(1)||'workspace';if(next===pageRef.current)return;const previous=pageRef.current;const commit=()=>commitNavigation(next);const guard=canvasNavigationGuard.current;if(guard&&!guard(commit)){history.replaceState(null,'',`${location.pathname}${location.search}${previous?`#${previous}`:''}`);return;}commit();};window.addEventListener('hashchange',h);return()=>{alive=false;window.removeEventListener('hashchange',h);};},[]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),6500);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{const keys=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(v=>!v);}if(e.key==='Escape')setMobileNav(false);};window.addEventListener('keydown',keys);return()=>window.removeEventListener('keydown',keys);},[]);
 // A background read only marks stale UI. It never overwrites a modal's unsaved edits.
 useEffect(()=>{let running=false;const check=async()=>{const current=stateRef.current;if(!current||document.hidden||running)return;running=true;try{const next=await api<{event_id:number}>(projectPath(current.project.id,'/changes'));if(stateRef.current?.project.id!==current.project.id)return;if(next.event_id!==(current.events[0]?.id||0))setChanged(true);}catch{}finally{running=false;}};const timer=setInterval(check,6500);window.addEventListener('focus',check);return()=>{clearInterval(timer);window.removeEventListener('focus',check);};},[]);
 function action(name:string,defaults:Record<string,any>={}){const command=meta?.commands.find(c=>c.name===name);if(!command){notify('That action is not available here.');return;}if(!state){notify('Open a project first.');return;}setDialog({command,defaults});}
 async function done(data:any,name:string){const command=meta?.commands.find(c=>c.name===name),label=command?.label||'Changes',projectId=stateRef.current?.project.id;const readOnly=!!command?.read_only,exportAction=name.startsWith('export.'),failed=data?.status==='failed'||data?.status==='cancelled';let refreshFailure='';if(!readOnly&&!exportAction&&!failed&&projectId){try{await refresh();}catch(e:any){refreshFailure=e?.message||'The project view could not be refreshed.';if(stateRef.current?.project.id===projectId)setWriteRefreshError({projectId,message:refreshFailure});}}if(exportAction){setResult(data);setResultModal({title:'Export ready',data});}else if(readOnly){setResultModal({title:label||'Project details',data});}else if(failed){notify(data.status==='failed'?'The image tool needs attention. Review its run details.':'The image tool run was stopped.');}else if(refreshFailure){notify(`${label} saved, but the project view could not refresh.`);}else {notify(`${label} saved to the project.`);} }
 async function retryWriteRefresh(warning:WriteRefreshWarning){if(stateRef.current?.project.id!==warning.projectId)return;try{await refresh();}catch(e:any){if(stateRef.current?.project.id===warning.projectId)setWriteRefreshError({projectId:warning.projectId,message:e?.message||'The project view could not be refreshed.'});}}
 const props=state&&session&&meta?{state,session,meta,action,select:setSelected,selected,refresh,notify,go,result,setResult}:null;
 const screens:Record<string,any>={overview:OverviewPage,intake:IntakePage,library:LibraryPage,outline:OutlinePage,guide:GuidePage,editor:EditorPage,frames:FramesPage,composition:CompositionPage,settings:SettingsPage,automation:AutomationPage};const Page=screens[page];
 return <div className="app-shell"><a className="skip-link" href="#main-content" onClick={(e:any)=>{e.preventDefault();document.getElementById('main-content')?.focus();}}>Skip to workspace</a><aside ref={navRef} className={`navigation ${mobileNav?'is-open':''}`} aria-label="Main navigation"><button className="wordmark" disabled={loading} onClick={()=>go('workspace')} aria-label="Storyboarder workspace"><span className="brand-mark"><Icon name="grid" size={23}/></span><span>Storyboarder<small>LOCAL PRODUCTION DESK</small></span></button><button disabled={loading} className={`workspace-switch ${page==='workspace'?'active':''}`} onClick={()=>go('workspace')}><Icon name="grid"/><span>Workspace</span></button><div className="nav-project"><span className="eyebrow">Current project</span><strong title={state?.project.title}>{state?displayTitle(state.project.title):'No project open'}</strong><small>{state?'Saved on this computer':'Create a project to begin'}</small></div><nav>{NAV.map(([key,label,icon])=><button key={key} aria-label={label} className={page===key?'active':''} disabled={loading||!state} onClick={()=>go(key)} aria-current={page===key?'page':undefined}><Icon name={icon}/><span>{label}</span>{key==='intake'&&state?.project.counts.intake?<span className="nav-count">{state.project.counts.intake}</span>:null}</button>)}</nav><div className="nav-bottom"><button data-action-search onClick={()=>setPalette(true)} disabled={!state}><Icon name="search"/>Search actions <kbd>⌘/Ctrl K</kbd></button><p><span className="local-dot"/>On this computer · v{session?.version||'1.0.0'}</p></div></aside>{mobileNav&&<button className="nav-scrim" onClick={()=>setMobileNav(false)} aria-label="Close navigation"/>}
 <div className="app-column"><header className="topbar"><button className="mobile-menu icon-button" aria-label="Open navigation" onClick={(e:any)=>{mobileNavOpener.current=e.currentTarget;setMobileNav(true);}}><Icon name="menu"/></button><div className="breadcrumbs"><button onClick={()=>go('workspace')}>Workspace</button>{state&&<><span>/</span><button onClick={()=>go('overview')}>{displayTitle(state.project.title)}</button></>}{page!=='workspace'&&<><span>/</span><strong>{NAV.find(n=>n[0]===page)?.[1]||'Project overview'}</strong></>}</div><div className="topbar-actions">{state&&<button className="text-button" onClick={()=>refresh().then(()=>notify('Project refreshed.')).catch(e=>setError(e.message))}><Icon name="refresh"/><span>Refresh</span></button>}<span className="local-indicator">On this computer</span></div></header>{changed&&<div className="external-change" role="status">This project was updated in the terminal or another window. Your unsaved edits are safe. <button onClick={()=>refresh().catch(e=>setError(e.message))}>Refresh project</button></div>}
 <div className={`work-area ${selected&&page!=='workspace'?'with-inspector':''}`}><main id="main-content" tabIndex={-1} className={`main-content ${page==='canvas'?'canvas-main':''}`}>{error&&<ErrorNotice error={error}><button onClick={()=>location.reload()}>Try again</button></ErrorNotice>}{writeRefreshError&&state&&writeRefreshError.projectId===state.project.id&&<div className="external-change" role="status">Your changes were saved, but the project view could not refresh. {writeRefreshError.message}<button onClick={()=>void retryWriteRefresh(writeRefreshError)}>Retry project refresh</button></div>}{loading?<div className="loading-state" role="status"><Icon name="grid" size={30}/><h2>Opening your project…</h2></div>:session&&meta&&(page==='workspace'||!state)?<WorkspacePage session={session} projects={session.projects} onOpen={open} onRefresh={refreshSession}/>:props&&page==='canvas'?<Canvas state={props.state} selected={selected} onSelect={setSelected} action={action} refresh={refresh} notify={notify} registerNavigationGuard={registerCanvasNavigationGuard}/>:props&&Page?<Page {...props}/>:props?<OverviewPage {...props}/>:!error?<Empty title="Open a project">Choose a project from Workspace or create a new one.</Empty>:null}</main>{state&&selected&&page!=='workspace'&&<Inspector state={state} id={selected} onClose={()=>setSelected(null)} onSelect={setSelected} action={action}/>}</div><footer className="app-footer">{page==='canvas'&&<span>Drag cards to arrange this view. The story sequence stays the same.</span>}{state&&<span>{state.media.length} reference images · {state.frames.filter(f=>f.state==='approved').length} approved storyboard frames</span>}</footer></div>
 {toast&&<div className="toast" role="status"><Icon name="check"/><span>{toast}</span><button aria-label="Dismiss notification" onClick={()=>setToast('')}><Icon name="close" size={16}/></button></div>}
 {dialog&&state&&meta&&<ActionDialog key={dialog.command.name+JSON.stringify(dialog.defaults)} command={dialog.command} defaults={dialog.defaults} state={state} meta={meta} onClose={()=>setDialog(null)} onDone={done} onReload={refresh}/>}
 {resultModal&&<Modal title={resultModal.title} onClose={()=>setResultModal(null)} wide><div className="modal-body">{resultModal.data?.archive&&state?<ExportLinks project={state.project.id} result={resultModal.data}/>:resultModal.data?.chain?<ContextView value={resultModal.data}/>:resultModal.data?.can_delete!==undefined?<div className="usage-summary"><p>{resultModal.data.can_delete?'This item is not used elsewhere.':'This item is used in these places:'}</p><ul>{Object.entries(resultModal.data).filter(([key,value])=>key!=='can_delete'&&Array.isArray(value)&&value.length>0).map(([key,value]:[string,any])=><li key={key}>{human(key)} · {value.length}</li>)}</ul></div>:<div className="muted"><p>Open the related project page to review these details.</p></div>}</div></Modal>}
 {palette&&meta&&<Modal title="Search actions" onClose={()=>setPalette(false)} wide><div className="modal-body"><label className="search"><Icon name="search"/><input autoFocus placeholder="Find an action…" aria-label="Find an action" value={paletteQuery} onChange={(e:any)=>setPaletteQuery(e.target.value)}/></label><div className="command-list">{meta.commands.filter(c=>!c.read_only&&c.browser&&!['entity.update','canvas.save','project.sync'].includes(c.name)&&c.label.toLowerCase().includes(paletteQuery.toLowerCase())).map(c=><button key={c.name} onClick={()=>{setPalette(false);action(c.name);}}><span>{c.label}</span><small>{c.destructive?'Confirmation required':''}</small></button>)}</div>{!meta.commands.some(c=>!c.read_only&&c.browser&&!['entity.update','canvas.save','project.sync'].includes(c.name)&&c.label.toLowerCase().includes(paletteQuery.toLowerCase()))&&<p className="muted">No matching actions.</p>}</div></Modal>}
 </div>;
}
