import React,{useEffect,useRef,useState,useMemo} from '../react';
import type {State,Entity,Graph,CanvasMode,Point,Viewport,Edge,ActionFn,Layout} from '../types';
import {api,projectPath,mediaUrl,runCommand} from '../api';
import {activeEntities,commandDefaults,kindLabel,human,statusLabel,roleLabel,displayTitle} from '../utils';
import {PageHeading,Icon,Empty,ErrorNotice,Modal,Badge} from '../components/Primitives';
import {NODE_W,NODE_H,tidy,fit,zoomAt,edgePath,descendants} from './geometry';
interface Props {state:State;selected:string|null;onSelect:(id:string)=>void;action:ActionFn;refresh:()=>Promise<State>;notify:(message:string)=>void;registerNavigationGuard:(guard:(commit:()=>void)=>boolean)=>()=>void}
function edgeLabel(edge:Edge){
 if(edge.kind==='relationship')return human(edge.label);
 if(edge.kind==='assignment'){const [role,selection]=edge.label.split(' · ');return `${roleLabel(role)} · ${selection==='specific image selected'?'Specific image selected':'No specific image selected'}`;}
 if(edge.kind==='location_default')return 'Location';
 return edge.label;
}
export function Canvas({state,selected,onSelect,action,refresh,notify,registerNavigationGuard}:Props){
 const [newKind,setNewKind]=useState('sequence');
 const [mode,setMode]=useState<CanvasMode>('story'),[scene,setScene]=useState(''),[sequence,setSequence]=useState('');
 const [query,setQuery]=useState(''),[assetType,setAssetType]=useState(''),[tag,setTag]=useState(''),[relation,setRelation]=useState('');
 const [graph,setGraph]=useState<Graph>({nodes:[],edges:[],mode:'story',total:0,truncated:false});
 const [positions,setPositions]=useState<Record<string,Point>>({}),[view,setView]=useState<Viewport>({x:50,y:50,scale:.7});
 const [hidden,setHidden]=useState<string[]>([]),[collapsed,setCollapsed]=useState<string[]>([]),[multi,setMulti]=useState<string[]>([]);
 const [error,setError]=useState(''),[loading,setLoading]=useState(false),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[layoutConflict,setLayoutConflict]=useState(false),[layoutConflictReady,setLayoutConflictReady]=useState(false),[pendingNavigation,setPendingNavigation]=useState<(()=>void)|null>(null),[linkFrom,setLinkFrom]=useState<string|null>(null);
 const [layoutName,setLayoutName]=useState('Working arrangement'),[layoutRevision,setLayoutRevision]=useState<number|undefined>(undefined),[layoutId,setLayoutId]=useState('');const layoutNameRef=useRef(layoutName);layoutNameRef.current=layoutName;
 const [selectedEdge,setSelectedEdge]=useState<Edge|null>(null),[deleteId,setDeleteId]=useState<string|null>(null),[usage,setUsage]=useState<any>(null);
 const stage=useRef<HTMLDivElement|null>(null);const drag=useRef<any>(null);const moved=useRef(false);const positionsRef=useRef(positions);positionsRef.current=positions;
 const dirtyRef=useRef(false),editVersion=useRef(0),savePromise=useRef<Promise<boolean>|null>(null);
 function markDirty(){editVersion.current+=1;dirtyRef.current=true;setDirty(true);}
 useEffect(()=>registerNavigationGuard(commit=>{if(!dirtyRef.current)return true;setPendingNavigation(()=>commit);return false;}),[registerNavigationGuard]);
 useEffect(()=>{if(!scene)setScene(activeEntities(state,'scene')[0]?.id||'');},[state.entities]);
 useEffect(()=>{const cancel=new AbortController();let active=true;setLoading(true);const params=new URLSearchParams({mode,query,limit:'250'});if(mode==='assets'){if(assetType)params.set('asset_type',assetType);if(tag)params.set('tag',tag);if(relation)params.set('relation',relation);}if(mode==='scene'&&scene)params.set('scene_id',scene);if(mode==='story'&&sequence)params.set('sequence_id',sequence);
 const timer=setTimeout(()=>{api<Graph>(projectPath(state.project.id,'/graph?'+params),'GET',undefined,cancel.signal).then(next=>{if(!active)return;setGraph(next);const base=tidy(next.nodes,next.edges,mode);const merged={...base,...positionsRef.current};setPositions(merged);const rect=stage.current?.getBoundingClientRect();if(rect&&query)setView(fit(Object.fromEntries(next.nodes.map(n=>[n.id,merged[n.id]])),rect.width,rect.height));setError('');}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));},query?150:0);return()=>{active=false;cancel.abort();clearTimeout(timer);};},[state,mode,scene,sequence,query,assetType,tag,relation]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty]);
 const suppressed=useMemo(()=>new Set([...hidden,...descendants(graph.nodes,collapsed)]),[hidden,collapsed,graph]);
 const visible=graph.nodes.filter(n=>!suppressed.has(n.id)),visibleIds=new Set(visible.map(n=>n.id));const edges=graph.edges.filter(e=>visibleIds.has(e.source)&&visibleIds.has(e.target));
 const bounds=()=>stage.current?.getBoundingClientRect();
 const fitView=()=>{const rect=bounds();if(rect){setView(fit(Object.fromEntries(visible.map(n=>[n.id,positions[n.id]||{x:0,y:0}])),rect.width,rect.height));markDirty();}};
 function restoreSaved(saved:Layout){setLayoutId(saved.id);setLayoutName(saved.name);layoutNameRef.current=saved.name;setLayoutRevision(saved.revision);setLayoutConflict(false);setLayoutConflictReady(false);setPositions(saved.positions);setHidden(saved.settings.hidden||[]);setCollapsed(saved.settings.collapsed||[]);if(saved.settings.viewport)setView(saved.settings.viewport);setScene(saved.settings.scene_id||scene);setSequence(saved.settings.sequence_id||'');const filters=saved.settings.filters||{};setQuery(filters.query||'');setAssetType(filters.asset_type||'');setTag(filters.tag||'');setRelation(filters.relation||'');dirtyRef.current=false;setDirty(false);}
 function switchMode(next:CanvasMode){if(next===mode)return;const change=()=>{setMode(next);setNewKind(next==='assets'?'asset':next==='scene'?'shot':'sequence');const sameName=state.layouts.find(layout=>layout.mode===next&&layout.name===layoutName);if(sameName)restoreSaved(sameName);else{setPositions({});setHidden([]);setCollapsed([]);setLayoutId('');setLayoutName('Working arrangement');layoutNameRef.current='Working arrangement';setLayoutRevision(undefined);setLayoutConflict(false);setLayoutConflictReady(false);dirtyRef.current=false;setDirty(false);setView({x:50,y:50,scale:.65});}setSelectedEdge(null);};if(dirtyRef.current){setPendingNavigation(()=>change);return;}change();}
 function select(node:Entity,event?:any){if(moved.current){moved.current=false;return;}if(linkFrom){const source=state.entities.find(n=>n.id===linkFrom);setLinkFrom(null);if(!source)return;if(source.id===node.id){setError('Choose a different item to connect to.');return;}
 if(source.kind==='asset'&&node.kind==='asset')action('link.create',{source_id:source.id,target_id:node.id});
 else if(source.kind==='shot'&&node.kind==='asset')action('assignment.create',{shot_id:source.id,asset_id:node.id});
 else if((source.kind==='sequence'&&node.kind==='scene')||(source.kind==='scene'&&node.kind==='shot'))action('story.move',{id:node.id,revision:node.revision,parent_id:source.id,position:0});
 else setError(`These items can’t be connected in that way. Connect library items to each other, add a reference to a shot, or place a scene or shot in the story.`);return;}
 onSelect(node.id);setSelectedEdge(null);setMulti(event?.shiftKey?(multi.includes(node.id)?multi.filter(id=>id!==node.id):[...multi,node.id]):[node.id]);}
 function startDrag(e:any,node?:Entity){if(e.button!==0&&e.button!==1)return;if((e.target as HTMLElement).closest('button,a,input,select'))return;if(linkFrom&&node)return;const rect=bounds();if(!rect)return;e.currentTarget.setPointerCapture(e.pointerId);moved.current=false;const ids=node?(multi.includes(node.id)?multi:[node.id]):[];if(node){onSelect(node.id);if(!multi.includes(node.id))setMulti([node.id]);}drag.current={kind:node?'node':'pan',pointer:e.pointerId,x:e.clientX,y:e.clientY,view:{...view},positions:{...positions},ids};e.preventDefault();e.stopPropagation();}
 function move(e:any){const d=drag.current;if(!d||d.pointer!==e.pointerId)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>3)moved.current=true;if(d.kind==='pan'){setView({...d.view,x:d.view.x+dx,y:d.view.y+dy});}else {setPositions(old=>{const next={...old};d.ids.forEach((id:string)=>{const p=d.positions[id]||{x:0,y:0};next[id]={x:p.x+dx/d.view.scale,y:p.y+dy/d.view.scale};});return next;});}markDirty();}
 function end(e:any){if(drag.current?.pointer===e.pointerId){drag.current=null;try{e.currentTarget.releasePointerCapture(e.pointerId);}catch{}}}
 function wheel(e:any){if(e.ctrlKey||e.metaKey){e.preventDefault();const r=bounds();if(r)setView(v=>zoomAt(v,{x:e.clientX-r.left,y:e.clientY-r.top},Math.exp(-e.deltaY*.002)));}else {e.preventDefault();setView(v=>({...v,x:v.x-e.deltaX,y:v.y-e.deltaY}));}markDirty();}
 useEffect(()=>{const el=stage.current;if(!el)return;el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[]);
 function key(e:any,node:Entity){if(e.key==='Enter'){e.preventDefault();e.stopPropagation();select(node,e);return;}if(e.key.toLowerCase()==='l'){e.preventDefault();setLinkFrom(node.id);notify('Choose an eligible destination, then press Enter or click it.');return;}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();requestDelete(node.id);return;}const delta:Record<string,Point>={ArrowLeft:{x:-1,y:0},ArrowRight:{x:1,y:0},ArrowUp:{x:0,y:-1},ArrowDown:{x:0,y:1}};if(delta[e.key]){e.preventDefault();const d=delta[e.key],step=e.shiftKey?50:10;setPositions(old=>({...old,[node.id]:{x:(old[node.id]?.x||0)+d.x*step,y:(old[node.id]?.y||0)+d.y*step}}));markDirty();}}
 function requestDelete(id:string){setDeleteId(id);setUsage(null);runCommand(state.project.id,'entity.usage',{id}).then(setUsage).catch(e=>setError(e.message));}
 async function refreshConflict(){const name=layoutName,layoutMode=mode;try{const latestState=await refresh();const latest=latestState.layouts.find(item=>item.name===name&&item.mode===layoutMode);if(!latest){setError('The saved arrangement is no longer available. Your local Canvas edits remain; rename the arrangement to save this draft separately.');setLayoutConflictReady(false);return;}setLayoutId(latest.id);setLayoutRevision(latest.revision);setLayoutConflictReady(true);setError('Latest saved revision loaded. Your local geometry is unchanged; review it, then reapply the draft explicitly.');}catch(e:any){setError(`Could not refresh the saved arrangement. Your local Canvas edits remain: ${e.message}`);}}
 async function save():Promise<boolean>{if(savePromise.current)return savePromise.current;if(!layoutName.trim()||(layoutConflict&&!layoutConflictReady))return false;const savedName=layoutName,version=editVersion.current,snapshot={name:layoutName,mode,positions,settings:{hidden,collapsed,viewport:view,filters:{query,asset_type:assetType,tag,relation},scene_id:scene,sequence_id:sequence},...(layoutRevision!==undefined?{revision:layoutRevision}:{})};setSaving(true);setError('');const operation=(async()=>{try{const result=await runCommand<Layout>(state.project.id,'canvas.save',snapshot);if(layoutNameRef.current===savedName){setLayoutId(result.id);setLayoutRevision(result.revision);}setLayoutConflict(false);setLayoutConflictReady(false);if(editVersion.current===version){dirtyRef.current=false;setDirty(false);}else{dirtyRef.current=true;setDirty(true);}let refreshFailure='';try{await refresh();}catch(e:any){refreshFailure=e.message;setError(`Arrangement saved, but the project view could not refresh: ${e.message}`);}notify(refreshFailure?'Arrangement saved, but the project view could not refresh.':'Canvas arrangement saved. Story order and connections stay the same.');return true;}catch(e:any){setError(e.message);if(e.code==='revision_conflict'){setLayoutConflict(true);setLayoutConflictReady(false);}return false;}finally{savePromise.current=null;setSaving(false);}})();savePromise.current=operation;return operation;}
 async function saveAndNavigate(){const saved=await save();if(saved&&pendingNavigation&&!dirtyRef.current){const commit=pendingNavigation;setPendingNavigation(null);commit();}else if(saved&&dirtyRef.current)setError('Canvas changed while the save was pending. Save again to keep those edits before leaving.');}
 function discardAndNavigate(){dirtyRef.current=false;setDirty(false);const commit=pendingNavigation;setPendingNavigation(null);commit?.();}
 function load(id:string){if(savePromise.current)return;const saved=state.layouts.find(l=>l.id===id);if(!saved)return;const restore=()=>restoreSaved(saved);if(dirtyRef.current){setPendingNavigation(()=>restore);return;}restore();}
 const selectedNode=state.entities.find(n=>n.id===selected);const tags=[...new Set(state.entities.flatMap(e=>e.tags))].sort();
 return <div className="canvas-page"><PageHeading eyebrow="Story map" title="Canvas" description="Arrange story cards and connect people, places, shots, and references." actions={<><select aria-label="Item to create" value={newKind} onChange={(e:any)=>setNewKind(e.target.value)}><option value="asset">Library item</option><option value="sequence">Sequence</option><option value="scene">Scene</option><option value="shot">Shot</option></select><button onClick={()=>action(newKind+'.create',newKind==='shot'&&scene?{parent_id:scene}:newKind==='scene'&&sequence?{parent_id:sequence}:{})}><Icon name="plus"/>Create {human(newKind).toLowerCase()}</button><button onClick={()=>action('link.create')}>Connect items</button></>}/>
 <div className="canvas-controls"><div className="segmented" aria-label="Canvas view">{([['story','Story flow'],['assets','Reference map'],['scene','Scene board']] as const).map(([value,label])=><button key={value} aria-pressed={mode===value} onClick={()=>switchMode(value)} disabled={saving}>{label}</button>)}</div><label className="search"><Icon name="search"/><input aria-label="Search canvas cards" placeholder="Find a card…" value={query} onChange={(e:any)=>{setQuery(e.target.value);markDirty();}}/></label>{mode==='scene'&&<select aria-label="Scene to show" value={scene} onChange={(e:any)=>{setScene(e.target.value);markDirty();}}><option value="">Choose a scene</option>{activeEntities(state,'scene').map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select>}{mode==='story'&&<select aria-label="Show sequence" value={sequence} onChange={(e:any)=>{setSequence(e.target.value);markDirty();}}><option value="">All sequences</option>{activeEntities(state,'sequence').map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select>}{mode==='assets'&&<><select aria-label="Filter by item type" value={assetType} onChange={(e:any)=>{setAssetType(e.target.value);markDirty();}}><option value="">All item types</option>{['character','location','prop','reference'].map(t=><option key={t} value={t}>{human(t)}</option>)}</select><select aria-label="Tag filter" value={tag} onChange={(e:any)=>{setTag(e.target.value);markDirty();}}><option value="">All tags</option>{tags.map(t=><option key={t} value={t}>{human(t)}</option>)}</select><select aria-label="Filter by connection" value={relation} onChange={(e:any)=>{setRelation(e.target.value);markDirty();}}><option value="">All connections</option>{['appears-at','alternate-view-of','wears','part-of','related-to'].map(t=><option key={t} value={t}>{human(t)}</option>)}</select></>}</div>
 {error&&<ErrorNotice error={error}/>} {linkFrom&&<div className="notice">Link from <strong>{displayTitle(state.entities.find(n=>n.id===linkFrom)?.title||'Selected item')}</strong>. Tab to a destination and press Enter, or click a node. <button onClick={()=>setLinkFrom(null)}>Cancel link</button></div>}
 <div className="canvas-layout-bar"><select aria-label="Saved arrangement" value={layoutId} disabled={saving} onChange={(e:any)=>load(e.target.value)}><option value="">New arrangement</option>{state.layouts.filter(l=>l.mode===mode).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><input aria-label="Arrangement name" value={layoutName} onChange={(e:any)=>{layoutNameRef.current=e.target.value;setLayoutName(e.target.value);if(e.target.value!==state.layouts.find(l=>l.id===layoutId)?.name){setLayoutRevision(undefined);setLayoutId('');setLayoutConflict(false);setLayoutConflictReady(false);}markDirty();}}/><button onClick={()=>void save()} disabled={!layoutName.trim()||saving||(layoutConflict&&!layoutConflictReady)}>{saving?'Saving…':'Save arrangement'}</button><button onClick={()=>{setPositions(tidy(graph.nodes,graph.edges,mode));markDirty();}}>Arrange cards</button><button onClick={fitView}>Fit canvas</button>{dirty&&<span role="status">Unsaved changes</span>}{hidden.length>0&&<button onClick={()=>{setHidden([]);markDirty();}}>Show {hidden.length} hidden cards</button>}</div>
 {layoutConflict&&<div className="notice warning" role="status"><p>The saved arrangement changed elsewhere. Your local Canvas edits remain. Refresh its latest revision before reapplying this draft.</p><button onClick={()=>void refreshConflict()} disabled={saving}>Refresh latest saved revision</button>{layoutConflictReady&&<button className="primary" onClick={()=>void save()} disabled={saving}>Reapply local draft</button>}</div>}
 <div ref={stage} className={`graph-stage ${linkFrom?'linking':''}`} tabIndex={0} aria-label="Interactive story canvas. Use Tab to select a card, arrow keys to move it, L to connect it, and Delete to review removal." onPointerDown={(e:any)=>startDrag(e)} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onKeyDown={(e:any)=>{if(e.key==='Escape'){setLinkFrom(null);setSelectedEdge(null);}}}>
 <div className="canvas-world" style={{transform:`translate(${view.x}px, ${view.y}px) scale(${view.scale})`}}><svg className="edge-layer" width="1" height="1" aria-label="Story and image connections"><defs><marker id="edge-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z"/></marker></defs>{edges.map(edge=>{const a=positions[edge.source],b=positions[edge.target];if(!a||!b)return null;const label=edgeLabel(edge);const curve=edgePath(a,b);return <g key={edge.id} className={`graph-edge ${edge.kind} ${selectedEdge?.id===edge.id?'is-selected':''}`}><path d={curve.path} markerEnd="url(#edge-arrow)"/><path d={curve.path} className="edge-hit" onClick={(e:any)=>{e.stopPropagation();setSelectedEdge(edge);}}/><g transform={`translate(${curve.label.x}, ${curve.label.y})`} role="button" tabIndex={0} aria-label={`${label} connection. Select to see options.`} onPointerDown={(e:any)=>e.stopPropagation()} onClick={()=>setSelectedEdge(edge)} onKeyDown={(e:any)=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();setSelectedEdge(edge);}}}><rect x={-Math.max(18,label.length*3.7+8)} y="-12" width={Math.max(36,label.length*7.4+16)} height="24" rx="4"/><text textAnchor="middle" dominantBaseline="central">{edge.kind==='order'?'# ':edge.kind==='assignment'?'↳ ':''}{label}</text></g></g>;})}</svg>
 {visible.map(node=>{const pos=positions[node.id]||{x:0,y:0},type=kindLabel(node);const thumbnail=node.thumbnail_media_id||node.reference_media_ids?.[0];return <article key={node.id} data-node-id={node.id} className={`graph-node ${type} ${selected===node.id||multi.includes(node.id)?'is-selected':''} ${linkFrom===node.id?'link-source':''}`} style={{width:NODE_W,height:NODE_H,transform:`translate(${pos.x}px,${pos.y}px)`}} tabIndex={0} role="button" aria-label={`${type}: ${node.title}. Used ${node.reference_count||0} times.`} aria-pressed={selected===node.id} onPointerDown={(e:any)=>startDrag(e,node)} onPointerMove={move} onPointerUp={end} onClick={(e:any)=>{e.stopPropagation();select(node,e);}} onKeyDown={(e:any)=>key(e,node)}>
 <div className="node-type"><span>{type}</span><span>{node.kind==='asset'?`${node.media_count||0} images`:`${String(node.position+1).padStart(2,'0')}`}</span></div>{thumbnail?<img className="node-image" src={mediaUrl(state.project.id,thumbnail)} alt={`${displayTitle(node.title)} ${node.frame_state?'storyboard image':'reference image'}`} draggable={false}/>:<div className="node-text-preview">{String(node.fields.action||node.fields.summary||node.fields.arc||node.description||'Add a description or story direction')}</div>}<div className="node-content"><h3>{displayTitle(node.title)}</h3><p>{node.kind==='shot'?`${node.fields.framing||'Framing not set'} · ${node.reference_count||0} references`:node.kind==='asset'?`${node.link_count||0} connections · used in ${node.reference_count||0} shots`:`${node.child_count||0} ${node.kind==='sequence'?'scenes':'shots'}`}</p><div className="node-footer">{node.frame_state?<Badge kind={node.frame_state}>{statusLabel(node.frame_state)} image</Badge>:node.tags.slice(0,2).map(t=><span key={t} className="tag">{t}</span>)}{node.child_count!>0&&node.kind!=='asset'&&<button aria-label={`${collapsed.includes(node.id)?'Expand':'Collapse'} ${displayTitle(node.title)}`} onClick={(e:any)=>{e.stopPropagation();setCollapsed(v=>v.includes(node.id)?v.filter(id=>id!==node.id):[...v,node.id]);markDirty();}}>{collapsed.includes(node.id)?'+':'−'}</button>}</div></div></article>;})}</div>
 {!visible.length&&!loading&&<Empty title={mode==='scene'?'Choose a scene to build its board':mode==='assets'?'Build your reference library':'Start your story map'} action={<button onClick={()=>action(mode==='assets'?'asset.create':mode==='scene'?'scene.create':'sequence.create')}>Create a {mode==='assets'?'reference item':mode==='scene'?'scene':'sequence'}</button>}>{mode==='assets'?'Add characters, places, props, and other references here. Their connections will appear as your library grows.':'Create items here or in the story outline. Story order and reference connections will appear as you build.'}</Empty>}
 <div className="canvas-zoom" onPointerDown={(e:any)=>e.stopPropagation()}><button aria-label="Zoom out" onClick={()=>{setView(v=>zoomAt(v,{x:200,y:200},.8));markDirty();}}>−</button><span>{Math.round(view.scale*100)}%</span><button aria-label="Zoom in" onClick={()=>{setView(v=>zoomAt(v,{x:200,y:200},1.25));markDirty();}}>+</button></div>
 </div><div className="canvas-status"><span>{loading?'Loading…':`${visible.length} cards · ${edges.length} connections`}{graph.truncated&&` · ${graph.total} matches; narrow your search to see more (up to 250 cards at a time)`}</span><span>Drag the background to move · Ctrl + scroll to zoom · Arrow keys to arrange · L to connect</span></div>
 {selectedNode&&<div className="selection-tools"><strong>{displayTitle(selectedNode.title)}</strong><button onClick={()=>action(selectedNode.kind+'.update',commandDefaults(selectedNode))}>Edit</button><button onClick={()=>setLinkFrom(selectedNode.id)}>Connect from here</button>{['sequence','scene','shot'].includes(selectedNode.kind)&&<button onClick={()=>action('story.move',commandDefaults(selectedNode))}>Move / reorder</button>}<button onClick={()=>requestDelete(selectedNode.id)}>Remove…</button></div>}
 {selectedEdge&&<div className="selection-tools"><strong>{edgeLabel(selectedEdge)}</strong><span>{selectedEdge.kind==='order'?'Story order':selectedEdge.kind==='assignment'?'Shot reference':selectedEdge.kind==='location_default'?`Location from ${human(selectedEdge.source_scope?.kind||'project').toLowerCase()}`:'Connection between library items'}</span>{selectedEdge.kind==='order'?<button onClick={()=>{const child=state.entities.find(n=>n.id===selectedEdge.target);if(child)action('story.move',commandDefaults(child));}}>Move in story</button>:selectedEdge.kind==='location_default'?<button onClick={()=>{const owner=state.entities.find(n=>n.id===selectedEdge.source);if(owner)action(owner.kind+'.update',commandDefaults(owner));}}>Edit location…</button>:<button onClick={()=>action(selectedEdge.kind==='assignment'?'assignment.remove':'link.remove',{id:selectedEdge.id,revision:selectedEdge.revision})}>Remove connection…</button>}<button onClick={()=>setSelectedEdge(null)}>Close</button></div>}
 {deleteId&&<Modal title="Remove this card?" onClose={()=>setDeleteId(null)}><div className="modal-body"><p>Hiding a card removes it from this arrangement. Archiving takes the item out of the active story; deleting removes it permanently.</p>{usage?<div className="usage-summary"><p>{usage.can_delete?'This item is not used elsewhere.':'This item is used in these places:'}</p>{Object.entries(usage).filter(([key,value])=>key!=='can_delete'&&Array.isArray(value)&&value.length>0).length>0&&<ul>{Object.entries(usage).filter(([key,value])=>key!=='can_delete'&&Array.isArray(value)&&value.length>0).map(([key,value]:[string,any])=><li key={key}>{human(key)} · {value.length}</li>)}</ul>}</div>:<p>Checking where this item is used…</p>}<div className="form-stack"><button onClick={()=>{setHidden([...hidden,deleteId]);markDirty();setDeleteId(null);}}>Hide from this arrangement</button><button onClick={()=>{const n=state.entities.find(n=>n.id===deleteId);if(n)action('entity.archive',commandDefaults(n));setDeleteId(null);}}>Archive item…</button><button className="danger" disabled={!usage?.can_delete} onClick={()=>{const n=state.entities.find(n=>n.id===deleteId);if(n)action('entity.delete',commandDefaults(n));setDeleteId(null);}}>Delete item…</button></div></div></Modal>}
 {pendingNavigation&&<Modal title="Unsaved canvas arrangement" onClose={()=>setPendingNavigation(null)}><div className="modal-body"><p>Your Canvas changes have not been saved. Save them to this arrangement, discard them, or stay on this view. The current geometry remains available while you decide.</p>{error&&<ErrorNotice error={error}/>}</div><div className="modal-footer"><button onClick={()=>setPendingNavigation(null)}>Stay</button><button onClick={discardAndNavigate}>Discard changes</button><button className="primary" disabled={!layoutName.trim()||saving||(layoutConflict&&!layoutConflictReady)} onClick={()=>void saveAndNavigate()}>{saving?'Saving…':'Save and continue'}</button></div></Modal>}
 </div>;
}
