import React,{useEffect,useLayoutEffect,useRef,useState,useMemo} from '../react';
import type {State,Entity,Graph,CanvasMode,Point,Viewport,Edge,ActionFn,Layout} from '../types';
import {api,projectPath,mediaUrl,runCommand} from '../api';
import {activeEntities,commandDefaults,kindLabel,human,statusLabel,roleLabel,displayTitle} from '../utils';
import {PageHeading,Icon,Empty,ErrorNotice,Modal,Badge} from '../components/Primitives';
import {NODE_W,NODE_H,tidy,fit,zoomAt,edgePath,descendants} from './geometry';
interface Props {state:State;draft?:CanvasDraft;onDraftChange:(draft:CanvasDraft)=>void;selected:string|null;onSelect:(id:string)=>void;action:ActionFn;refresh:()=>Promise<State>;notify:(message:string)=>void;registerNavigationGuard:(guard:(commit:()=>void)=>boolean)=>()=>void}
interface LayoutDraft {name:string;mode:CanvasMode;positions:Record<string,Point>;settings:Layout['settings']}
interface FieldValue {present:boolean;value?:any}
interface LayoutChange {key:string;path:string[];label:string;base:FieldValue;local:FieldValue;saved:FieldValue;conflict:boolean}
interface LayoutReview {remote:Layout;local:LayoutDraft;merged:LayoutDraft;changes:LayoutChange[];choices:Record<string,'local'|'saved'>;editVersion:number}
// App owns this session-only presentation snapshot, isolated by project ID.
export interface CanvasDraft {
 mode:CanvasMode;scene:string;sequence:string;query:string;assetType:string;tag:string;relation:string;
 positions:Record<string,Point>;view:Viewport;hidden:string[];collapsed:string[];
 layoutName:string;layoutRevision:number|undefined;layoutId:string;dirty:boolean;
 baseline:Layout|null;layoutConflict:boolean;layoutUnavailable:boolean;conflictId:string|null;review:LayoutReview|null;
 editVersion:number;error:string;
}
function clone<T>(value:T):T{return JSON.parse(JSON.stringify(value));}
function flatten(value:any,path:string[]=[],result=new Map<string,{path:string[];value:FieldValue}>()):Map<string,{path:string[];value:FieldValue}>{
 const isObject=value!==null&&typeof value==='object'&&!Array.isArray(value);
 const entries=isObject?Object.entries(value):[];
 if(entries.length){for(const [key,child] of entries)flatten(child,[...path,key],result);}
 else if(path.length)result.set(JSON.stringify(path),{path,value:{present:true,value:clone(value)}});
 return result;
}
function valueAt(fields:Map<string,{path:string[];value:FieldValue}>,key:string):FieldValue{return fields.get(key)?.value||{present:false};}
function stableValue(value:any):any{if(Array.isArray(value))return value.map(stableValue);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,stableValue(value[key])]));return value;}
function sameValue(a:FieldValue,b:FieldValue):boolean{return a.present===b.present&&(!a.present||JSON.stringify(stableValue(a.value))===JSON.stringify(stableValue(b.value)));}
function writePath(target:any,path:string[],entry:FieldValue){let parent=target;for(const key of path.slice(0,-1)){if(!parent[key]||typeof parent[key]!=='object'||Array.isArray(parent[key]))parent[key]={};parent=parent[key];}const leaf=path[path.length-1];if(!entry.present)delete parent[leaf];else parent[leaf]=clone(entry.value);}
function compareLayouts(base:LayoutDraft|null,local:LayoutDraft,saved:LayoutDraft){
 const baseFields=flatten(base||{}),localFields=flatten(local),savedFields=flatten(saved),keys=new Set([...baseFields.keys(),...localFields.keys(),...savedFields.keys()]);
 const merged=clone(base||local) as LayoutDraft,changes:LayoutChange[]=[];
 for(const key of keys){const path=(localFields.get(key)||savedFields.get(key)||baseFields.get(key))!.path;const before=valueAt(baseFields,key),ours=valueAt(localFields,key),theirs=valueAt(savedFields,key);const localChanged=!sameValue(ours,before),savedChanged=!sameValue(theirs,before),conflict=base?localChanged&&savedChanged&&!sameValue(ours,theirs):!sameValue(ours,theirs);const selected=conflict?ours:localChanged?ours:theirs;writePath(merged,path,selected);if(!sameValue(ours,theirs)||localChanged||savedChanged){changes.push({key,path,base:before,local:ours,saved:theirs,conflict,label:path.join('.')});}}
 return {merged,changes};
}
function applyNewLocalEdits(reference:LayoutDraft,current:LayoutDraft,saved:LayoutDraft):LayoutDraft{const before=flatten(reference),now=flatten(current),result=clone(saved);for(const key of new Set([...before.keys(),...now.keys()])){const old=valueAt(before,key),next=valueAt(now,key);if(!sameValue(old,next)){const path=(now.get(key)||before.get(key))!.path;writePath(result,path,next);}}return result;}
function asLayoutDraft(layout:Layout):LayoutDraft{return {name:layout.name,mode:layout.mode,positions:clone(layout.positions),settings:clone(layout.settings)};}
function draftFromLayoutResult(layout:Layout):Layout{return {id:layout.id,name:layout.name,mode:layout.mode,positions:clone(layout.positions),settings:clone(layout.settings),revision:layout.revision,updated_at:layout.updated_at};}
function edgeLabel(edge:Edge){
 if(edge.kind==='relationship')return human(edge.label);
 if(edge.kind==='assignment'){const [role,selection]=edge.label.split(' · ');return `${roleLabel(role)} · ${selection==='specific image selected'?'Specific image selected':'No specific image selected'}`;}
 if(edge.kind==='location_default')return 'Location';
 return edge.label;
}
export function Canvas({state,draft,onDraftChange,selected,onSelect,action,refresh,notify,registerNavigationGuard}:Props){
 const [newKind,setNewKind]=useState(draft?.mode==='assets'?'asset':draft?.mode==='scene'?'shot':'sequence');
 const [mode,setMode]=useState<CanvasMode>(draft?.mode||'story'),[scene,setScene]=useState(draft?.scene||''),[sequence,setSequence]=useState(draft?.sequence||'');
 const [query,setQuery]=useState(draft?.query||''),[assetType,setAssetType]=useState(draft?.assetType||''),[tag,setTag]=useState(draft?.tag||''),[relation,setRelation]=useState(draft?.relation||'');
 const [graph,setGraph]=useState<Graph>({nodes:[],edges:[],mode:'story',total:0,truncated:false});
 const [positions,setPositions]=useState<Record<string,Point>>(draft?.positions||{}),[view,setView]=useState<Viewport>(draft?.view||{x:50,y:50,scale:.7});
 const [hidden,setHidden]=useState<string[]>(draft?.hidden||[]),[collapsed,setCollapsed]=useState<string[]>(draft?.collapsed||[]),[multi,setMulti]=useState<string[]>([]);
 const [error,setError]=useState(draft?.error||''),[loading,setLoading]=useState(false),[dirty,setDirty]=useState(draft?.dirty||false),[saving,setSaving]=useState(false),[layoutConflict,setLayoutConflict]=useState(draft?.layoutConflict||false),[layoutUnavailable,setLayoutUnavailable]=useState(draft?.layoutUnavailable||false),[conflictId,setConflictId]=useState<string|null>(draft?.conflictId||null),[review,setReview]=useState<LayoutReview|null>(draft?.review||null),[refreshingConflict,setRefreshingConflict]=useState(false),[pendingNavigation,setPendingNavigation]=useState<(()=>void)|null>(null),[linkFrom,setLinkFrom]=useState<string|null>(null);
 const [layoutName,setLayoutName]=useState(draft?.layoutName||'Working arrangement'),[layoutRevision,setLayoutRevision]=useState<number|undefined>(draft?.layoutRevision),[layoutId,setLayoutId]=useState(draft?.layoutId||'');const layoutNameRef=useRef(layoutName);layoutNameRef.current=layoutName;
 const [selectedEdge,setSelectedEdge]=useState<Edge|null>(null),[deleteId,setDeleteId]=useState<string|null>(null),[usage,setUsage]=useState<any>(null),[usageLoading,setUsageLoading]=useState(false),[usageError,setUsageError]=useState('');
 const usageRequest=useRef(0),deleteTarget=useRef<string|null>(null);
 const stage=useRef<HTMLDivElement|null>(null);const drag=useRef<any>(null);const moved=useRef(false);const positionsRef=useRef(positions);positionsRef.current=positions;const layoutBaseline=useRef<Layout|null>(draft?.baseline||null);const restoreView=useRef(!!draft);
 const currentDraft:LayoutDraft={name:layoutName,mode,positions,settings:{hidden,collapsed,viewport:view,filters:{query,asset_type:assetType,tag,relation},scene_id:scene,sequence_id:sequence}};const draftRef=useRef(currentDraft);draftRef.current=currentDraft;
 const dirtyRef=useRef(draft?.dirty||false),editVersion=useRef(draft?.editVersion||0),savePromise=useRef<Promise<boolean>|null>(null);
 function markDirty(){editVersion.current+=1;dirtyRef.current=true;setDirty(true);}
 useEffect(()=>registerNavigationGuard(commit=>{if(!savePromise.current)return true;setPendingNavigation(()=>commit);return false;}),[registerNavigationGuard]);
 useEffect(()=>{if(!scene)setScene(activeEntities(state,'scene')[0]?.id||'');},[state.entities]);
 useEffect(()=>{const cancel=new AbortController();let active=true;setLoading(true);const params=new URLSearchParams({mode,query,limit:'250'});if(mode==='assets'){if(assetType)params.set('asset_type',assetType);if(tag)params.set('tag',tag);if(relation)params.set('relation',relation);}if(mode==='scene'&&scene)params.set('scene_id',scene);if(mode==='story'&&sequence)params.set('sequence_id',sequence);
 const timer=setTimeout(()=>{api<Graph>(projectPath(state.project.id,'/graph?'+params),'GET',undefined,cancel.signal).then(next=>{if(!active)return;setGraph(next);const base=tidy(next.nodes,next.edges,mode);const merged={...base,...positionsRef.current};setPositions(merged);const rect=stage.current?.getBoundingClientRect();if(rect&&query&&!restoreView.current)setView(fit(Object.fromEntries(next.nodes.map(n=>[n.id,merged[n.id]])),rect.width,rect.height));restoreView.current=false;}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));},query?150:0);return()=>{active=false;cancel.abort();clearTimeout(timer);};},[state,mode,scene,sequence,query,assetType,tag,relation]);
 // Capture before the next navigation event; preserve the exact CAS baseline and conflict choices.
 function publishDraft(overrides:Partial<CanvasDraft>={}){onDraftChange({mode,scene,sequence,query,assetType,tag,relation,positions,view,hidden,collapsed,layoutName,layoutRevision,layoutId,dirty,baseline:layoutBaseline.current,layoutConflict,layoutUnavailable,conflictId,review,editVersion:editVersion.current,error,...overrides});}
 function snapshotFields(next:LayoutDraft):Partial<CanvasDraft>{const settings=next.settings,filters=settings.filters||{};return {layoutName:next.name,mode:next.mode,positions:next.positions,hidden:settings.hidden||[],collapsed:settings.collapsed||[],view:settings.viewport||view,query:filters.query||'',assetType:filters.asset_type||'',tag:filters.tag||'',relation:filters.relation||'',scene:settings.scene_id||'',sequence:settings.sequence_id||''};}
 useLayoutEffect(()=>{publishDraft();},[onDraftChange,mode,scene,sequence,query,assetType,tag,relation,positions,view,hidden,collapsed,layoutName,layoutRevision,layoutId,dirty,layoutConflict,layoutUnavailable,conflictId,review,error]);

 const suppressed=useMemo(()=>new Set([...hidden,...descendants(graph.nodes,collapsed)]),[hidden,collapsed,graph]);
 const visible=graph.nodes.filter(n=>!suppressed.has(n.id)),visibleIds=new Set(visible.map(n=>n.id));const edges=graph.edges.filter(e=>visibleIds.has(e.source)&&visibleIds.has(e.target));
 const bounds=()=>stage.current?.getBoundingClientRect();
 const fitView=()=>{const rect=bounds();if(rect){setView(fit(Object.fromEntries(visible.map(n=>[n.id,positions[n.id]||{x:0,y:0}])),rect.width,rect.height));markDirty();}};
 function restoreSaved(saved:Layout){layoutBaseline.current=draftFromLayoutResult(saved);setLayoutId(saved.id);setLayoutName(saved.name);layoutNameRef.current=saved.name;setLayoutRevision(saved.revision);setLayoutConflict(false);setLayoutUnavailable(false);setConflictId(null);setReview(null);setPositions(saved.positions);setHidden(saved.settings.hidden||[]);setCollapsed(saved.settings.collapsed||[]);if(saved.settings.viewport)setView(saved.settings.viewport);setScene(saved.settings.scene_id||scene);setSequence(saved.settings.sequence_id||'');const filters=saved.settings.filters||{};setQuery(filters.query||'');setAssetType(filters.asset_type||'');setTag(filters.tag||'');setRelation(filters.relation||'');dirtyRef.current=false;setDirty(false);}
 function switchMode(next:CanvasMode){if(next===mode)return;const change=()=>{setMode(next);setNewKind(next==='assets'?'asset':next==='scene'?'shot':'sequence');const sameName=state.layouts.find(layout=>layout.mode===next&&layout.name===layoutName);if(sameName)restoreSaved(sameName);else{layoutBaseline.current=null;setPositions({});setHidden([]);setCollapsed([]);setLayoutId('');setLayoutName('Working arrangement');layoutNameRef.current='Working arrangement';setLayoutRevision(undefined);setLayoutConflict(false);setLayoutUnavailable(false);setConflictId(null);setReview(null);dirtyRef.current=false;setDirty(false);setView({x:50,y:50,scale:.65});}setSelectedEdge(null);};if(dirtyRef.current){setPendingNavigation(()=>change);return;}change();}
 function select(node:Entity,event?:any){if(moved.current){moved.current=false;return;}if(linkFrom){const source=state.entities.find(n=>n.id===linkFrom);setLinkFrom(null);if(!source)return;if(source.id===node.id){setError('Choose a different item to connect to.');return;}
 if(source.kind==='asset'&&node.kind==='asset')action('link.create',{source_id:source.id,target_id:node.id});
 else if(source.kind==='shot'&&node.kind==='asset')action('assignment.create',{shot_id:source.id,asset_id:node.id});
 else if((source.kind==='sequence'&&node.kind==='scene')||(source.kind==='scene'&&node.kind==='shot'))action('story.move',{id:node.id,revision:node.revision,parent_id:source.id,position:0});
 else setError(`These items can’t be connected in that way. Connect library items to each other, add a reference to a shot, or place a scene or shot in the story.`);return;}
 onSelect(node.id);setSelectedEdge(null);setMulti(event?.shiftKey?(multi.includes(node.id)?multi.filter(id=>id!==node.id):[...multi,node.id]):[node.id]);}
 function startDrag(e:any,node?:Entity){if(e.button!==0&&e.button!==1)return;if((e.target as HTMLElement).closest('button,a,input,select'))return;if(linkFrom&&node)return;const rect=bounds();if(!rect)return;e.currentTarget.setPointerCapture(e.pointerId);moved.current=false;const ids=node?(multi.includes(node.id)?multi:[node.id]):[];if(node){onSelect(node.id);if(!multi.includes(node.id))setMulti([node.id]);}drag.current={kind:node?'node':'pan',pointer:e.pointerId,x:e.clientX,y:e.clientY,view:{...view},positions:{...positions},ids};e.preventDefault();e.stopPropagation();}
 function move(e:any){const d=drag.current;if(!d||d.pointer!==e.pointerId)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>3)moved.current=true;if(d.kind==='pan'){setView({...d.view,x:d.view.x+dx,y:d.view.y+dy});}else {setPositions(old=>{const next={...old};d.ids.forEach((id:string)=>{const p=d.positions[id]||{x:0,y:0};next[id]={x:p.x+dx/d.view.scale,y:p.y+dy/d.view.scale};});return next;});}markDirty();}
 function end(e:any){if(drag.current?.pointer===e.pointerId){drag.current=null;try{e.currentTarget.releasePointerCapture(e.pointerId);}catch{}}}
 function wheel(e:any){if(e.ctrlKey||e.metaKey){e.preventDefault();const r=bounds();if(r)setView(v=>zoomAt(v,{x:e.clientX-r.left,y:e.clientY-r.top},Math.exp(-e.deltaY*.002)));}else {e.preventDefault();setView(v=>({...v,x:v.x-e.deltaX,y:v.y-e.deltaY}));}markDirty();}
 useEffect(()=>{const el=stage.current;if(!el)return;el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[]);
 function key(e:any,node:Entity){const target=e.target as HTMLElement|null;if(target&&target!==e.currentTarget&&target.closest('button,a,input,select,textarea,[contenteditable="true"]'))return;if(e.key==='Enter'||e.key===' '||e.code==='Space'){e.preventDefault();e.stopPropagation();select(node,e);return;}if(e.key.toLowerCase()==='l'){e.preventDefault();setLinkFrom(node.id);notify('Choose an eligible destination, then press Enter or click it.');return;}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();requestDelete(node.id);return;}const delta:Record<string,Point>={ArrowLeft:{x:-1,y:0},ArrowRight:{x:1,y:0},ArrowUp:{x:0,y:-1},ArrowDown:{x:0,y:1}};if(delta[e.key]){e.preventDefault();const d=delta[e.key],step=e.shiftKey?50:10;setPositions(old=>({...old,[node.id]:{x:(old[node.id]?.x||0)+d.x*step,y:(old[node.id]?.y||0)+d.y*step}}));markDirty();}}
 async function refreshUsage(id:string){const request=++usageRequest.current;deleteTarget.current=id;setUsage(null);setUsageError('');setUsageLoading(true);try{const result=await runCommand(state.project.id,'entity.usage',{id});if(request===usageRequest.current&&deleteTarget.current===id)setUsage(result);}catch(e:any){if(request===usageRequest.current&&deleteTarget.current===id)setUsageError(e.message||'Could not check where this item is used.');}finally{if(request===usageRequest.current&&deleteTarget.current===id)setUsageLoading(false);}}
 function closeDelete(){usageRequest.current+=1;deleteTarget.current=null;setDeleteId(null);setUsage(null);setUsageError('');setUsageLoading(false);}
 function requestDelete(id:string){deleteTarget.current=id;setDeleteId(id);void refreshUsage(id);}
 async function refreshConflict(){setRefreshingConflict(true);try{const latestState=await refresh();const stableId=conflictId||layoutId;const latest=stableId?latestState.layouts.find(item=>item.id===stableId):latestState.layouts.find(item=>item.name===layoutName&&item.mode===mode);if(!latest){setReview(null);setLayoutUnavailable(true);setError('This saved arrangement is no longer available. Your local Canvas edits remain. Use Save as new to keep them under a new name.');return;}setLayoutUnavailable(false);const local=clone(draftRef.current);const base=layoutBaseline.current?.id===latest.id?asLayoutDraft(layoutBaseline.current):null;const compared=compareLayouts(base,local,asLayoutDraft(latest));setReview({remote:draftFromLayoutResult(latest),local,merged:compared.merged,changes:compared.changes,choices:{},editVersion:editVersion.current});setConflictId(latest.id);setError('Latest saved revision loaded. Compare the saved and local fields, choose each conflicting value, then reapply.');}catch(e:any){setError(`Could not refresh the saved arrangement. Your local Canvas edits remain: ${e.message}`);}finally{setRefreshingConflict(false);}}
 function labelChange(path:string[]){if(path[0]==='positions'){const id=path[1],node=state.entities.find(item=>item.id===id);return `Card ${node?displayTitle(node.title):'removed card'} (${id}) · ${path[2]==='x'?'horizontal position (x)':'vertical position (y)'}`;}if(path[0]==='settings')return `Canvas setting · ${path.slice(1).join(' · ')}`;if(path[0]==='name')return 'Arrangement name';if(path[0]==='mode')return 'Canvas view';return path.join(' · ');}
 function resolvedReviewDraft(active:LayoutReview):LayoutDraft{const next=clone(active.merged);for(const change of active.changes){if(!change.conflict)continue;const choice=active.choices[change.key];if(choice)writePath(next,change.path,choice==='local'?change.local:change.saved);}return next;}
 function setCanvasDraft(next:LayoutDraft){setLayoutName(next.name);layoutNameRef.current=next.name;setMode(next.mode);setPositions(clone(next.positions));const settings=next.settings||{};setHidden(settings.hidden||[]);setCollapsed(settings.collapsed||[]);if(settings.viewport)setView(settings.viewport);const filters=settings.filters||{};setQuery(filters.query||'');setAssetType(filters.asset_type||'');setTag(filters.tag||'');setRelation(filters.relation||'');setScene(settings.scene_id||'');setSequence(settings.sequence_id||'');}
 function saveAsNew(){const base=`${layoutName.trim()||'Working arrangement'} copy`;let next=base,index=2;while(state.layouts.some(item=>item.mode===mode&&item.name===next)){next=`${base} ${index++}`;}setLayoutId('');setLayoutRevision(undefined);layoutBaseline.current=null;setLayoutConflict(false);setLayoutUnavailable(false);setConflictId(null);setReview(null);setLayoutName(next);layoutNameRef.current=next;setError('');markDirty();}
 async function save(approved?:{draft:LayoutDraft;id:string;revision:number;reference:LayoutDraft}):Promise<boolean>{if(savePromise.current)return savePromise.current;if(!layoutName.trim()||(layoutConflict&&!approved))return false;if(approved&&review?.changes.some(change=>change.conflict&&!review.choices[change.key]))return false;const version=editVersion.current,requested=approved?applyNewLocalEdits(approved.reference,draftRef.current,approved.draft):clone(draftRef.current),snapshot={name:requested.name,mode:requested.mode,positions:requested.positions,settings:requested.settings,...((approved?.revision??layoutRevision)!==undefined?{revision:approved?.revision??layoutRevision}:{}),...(approved?.id||layoutId?{layout_id:approved?.id||layoutId}:{})};setSaving(true);setError('');const operation=(async()=>{try{const result=await runCommand<Layout>(state.project.id,'canvas.save',snapshot);const saved=draftFromLayoutResult(result);const current=editVersion.current===version?saved:applyNewLocalEdits(requested,draftRef.current,asLayoutDraft(result));if(approved)setCanvasDraft(current);layoutBaseline.current=saved;setLayoutId(result.id);setLayoutName(current.name);layoutNameRef.current=current.name;setLayoutRevision(result.revision);setLayoutConflict(false);setLayoutUnavailable(false);setConflictId(null);setReview(null);const hasNewerEdits=editVersion.current!==version;if(!hasNewerEdits){dirtyRef.current=false;setDirty(false);}else{dirtyRef.current=true;setDirty(true);}publishDraft({...snapshotFields(current),baseline:saved,layoutId:result.id,layoutRevision:result.revision,dirty:hasNewerEdits,layoutConflict:false,layoutUnavailable:false,conflictId:null,review:null,error:''});let refreshFailure='';try{await refresh();}catch(e:any){refreshFailure=e.message;setError(`Arrangement saved, but the project view could not refresh: ${e.message}`);}notify(refreshFailure?'Arrangement saved, but the project view could not refresh.':'Canvas arrangement saved. Story order and connections stay the same.');return true;}catch(e:any){setError(e.message);if(e.code==='revision_conflict'){setLayoutConflict(true);setLayoutUnavailable(false);setConflictId(e.details?.id?String(e.details.id):layoutId||null);setReview(null);}return false;}finally{savePromise.current=null;setSaving(false);}})();savePromise.current=operation;return operation;}
 async function reapplyConflict(){if(!review)return;const active=review;if(active.changes.some(change=>change.conflict&&!active.choices[change.key]))return;const draft=resolvedReviewDraft(active);const saved=await save({draft,id:active.remote.id,revision:active.remote.revision,reference:active.local});if(saved&&pendingNavigation&&!dirtyRef.current){const commit=pendingNavigation;setPendingNavigation(null);commit();}}
 async function saveAndNavigate(){if(layoutConflict&&review){await reapplyConflict();return;}const saved=await save();if(saved&&pendingNavigation&&!dirtyRef.current){const commit=pendingNavigation;setPendingNavigation(null);commit();}else if(saved&&dirtyRef.current)setError('Canvas changed while the save was pending. Save again to keep those edits before leaving.');}
 function discardAndNavigate(){if(savePromise.current)return;const baseline=layoutBaseline.current;const next:LayoutDraft=baseline?asLayoutDraft(baseline):{name:layoutName,mode,positions:{},settings:{viewport:{x:50,y:50,scale:.7}}};setCanvasDraft(next);dirtyRef.current=false;setDirty(false);setLayoutConflict(false);setLayoutUnavailable(false);setConflictId(null);setReview(null);setError('');publishDraft({...snapshotFields(next),dirty:false,layoutConflict:false,layoutUnavailable:false,conflictId:null,review:null,error:''});const commit=pendingNavigation;setPendingNavigation(null);commit?.();}
 function load(id:string){if(savePromise.current)return;const saved=state.layouts.find(l=>l.id===id);if(!saved)return;const restore=()=>restoreSaved(saved);if(dirtyRef.current){setPendingNavigation(()=>restore);return;}restore();}
 const conflictPanel=layoutConflict?<div className="notice warning" role="status"><p>{layoutUnavailable?'This saved arrangement is no longer available. Your local Canvas edits remain. Save them as a new arrangement to keep them.':'The saved arrangement changed elsewhere. Your local Canvas edits remain. Refresh the latest saved version, compare the changed fields, and choose how to resolve each overlap.'}</p><button onClick={()=>void refreshConflict()} disabled={saving||refreshingConflict}>{refreshingConflict?'Refreshing saved version…':'Refresh latest saved revision'}</button>{layoutUnavailable&&<button onClick={saveAsNew} disabled={saving}>Save as new arrangement</button>}{review&&<div className="layout-conflict-review" aria-label="Saved and local arrangement changes"><h3>Saved version {review.remote.revision} · compare changes</h3>{review.changes.length?<ul>{review.changes.map(change=><li key={change.key} data-conflict-path={change.key}><strong>{labelChange(change.path)}</strong><div className="layout-conflict-values"><span>Saved: {change.saved.present?JSON.stringify(change.saved.value):'Not set'}</span><span>Local: {change.local.present?JSON.stringify(change.local.value):'Not set'}</span></div>{change.conflict?<div className="layout-conflict-choices"><button aria-pressed={review.choices[change.key]==='local'} onClick={()=>setReview(old=>old?{...old,choices:{...old.choices,[change.key]:'local'}}:old)}>Keep local</button><button aria-pressed={review.choices[change.key]==='saved'} onClick={()=>setReview(old=>old?{...old,choices:{...old.choices,[change.key]:'saved'}}:old)}>Use saved</button></div>:<small>These edits do not overlap and will be merged automatically.</small>}</li>)}</ul>:<p>The saved and local arrangement fields match. You can safely reapply the current draft.</p>}<button className="primary" onClick={()=>void reapplyConflict()} disabled={saving||review.changes.some(change=>change.conflict&&!review.choices[change.key])}>Reapply merged arrangement</button></div>}</div>:null;
 const selectedNode=state.entities.find(n=>n.id===selected);const tags=[...new Set(state.entities.flatMap(e=>e.tags))].sort();
 return <div className="canvas-page"><PageHeading eyebrow="Story map" title="Canvas" description="Arrange story cards and connect people, places, shots, and references." actions={<><select aria-label="Item to create" value={newKind} onChange={(e:any)=>setNewKind(e.target.value)}><option value="asset">Library item</option><option value="sequence">Sequence</option><option value="scene">Scene</option><option value="shot">Shot</option></select><button onClick={()=>action(newKind+'.create',newKind==='shot'&&scene?{parent_id:scene}:newKind==='scene'&&sequence?{parent_id:sequence}:{})}><Icon name="plus"/>Create {human(newKind).toLowerCase()}</button><button onClick={()=>action('link.create')}>Connect items</button></>}/>
 <div className="canvas-controls"><div className="segmented" aria-label="Canvas view">{([['story','Story flow'],['assets','Reference map'],['scene','Scene board']] as const).map(([value,label])=><button key={value} aria-pressed={mode===value} onClick={()=>switchMode(value)} disabled={saving}>{label}</button>)}</div><label className="search"><Icon name="search"/><input aria-label="Search canvas cards" placeholder="Find a card…" value={query} onChange={(e:any)=>{setQuery(e.target.value);markDirty();}}/></label>{mode==='scene'&&<select aria-label="Scene to show" value={scene} onChange={(e:any)=>{setScene(e.target.value);markDirty();}}><option value="">Choose a scene</option>{activeEntities(state,'scene').map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select>}{mode==='story'&&<select aria-label="Show sequence" value={sequence} onChange={(e:any)=>{setSequence(e.target.value);markDirty();}}><option value="">All sequences</option>{activeEntities(state,'sequence').map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select>}{mode==='assets'&&<><select aria-label="Filter by item type" value={assetType} onChange={(e:any)=>{setAssetType(e.target.value);markDirty();}}><option value="">All item types</option>{['character','location','prop','reference'].map(t=><option key={t} value={t}>{human(t)}</option>)}</select><select aria-label="Tag filter" value={tag} onChange={(e:any)=>{setTag(e.target.value);markDirty();}}><option value="">All tags</option>{tags.map(t=><option key={t} value={t}>{human(t)}</option>)}</select><select aria-label="Filter by connection" value={relation} onChange={(e:any)=>{setRelation(e.target.value);markDirty();}}><option value="">All connections</option>{['appears-at','alternate-view-of','wears','part-of','related-to'].map(t=><option key={t} value={t}>{human(t)}</option>)}</select></>}</div>
 {error&&<ErrorNotice error={error}/>} {linkFrom&&<div className="notice">Link from <strong>{displayTitle(state.entities.find(n=>n.id===linkFrom)?.title||'Selected item')}</strong>. Tab to a destination and press Enter, or click a node. <button onClick={()=>setLinkFrom(null)}>Cancel link</button></div>}
 <div className="canvas-layout-bar"><select aria-label="Saved arrangement" value={layoutId} disabled={saving} onChange={(e:any)=>load(e.target.value)}><option value="">New arrangement</option>{layoutId&&!state.layouts.some(l=>l.id===layoutId)&&<option value={layoutId}>Unavailable arrangement</option>}{state.layouts.filter(l=>l.mode===mode).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><input aria-label="Arrangement name" value={layoutName} onChange={(e:any)=>{layoutNameRef.current=e.target.value;setLayoutName(e.target.value);markDirty();}}/><button onClick={()=>void save()} disabled={!layoutName.trim()||saving||layoutConflict}>{saving?'Saving…':'Save arrangement'}</button>{layoutId&&<button onClick={saveAsNew} disabled={saving}>Save as new</button>}<button onClick={()=>{setPositions(tidy(graph.nodes,graph.edges,mode));markDirty();}}>Arrange cards</button><button onClick={fitView}>Fit canvas</button>{dirty&&<span role="status">Unsaved changes</span>}{hidden.length>0&&<button onClick={()=>{setHidden([]);markDirty();}}>Show {hidden.length} hidden cards</button>}</div>
 {conflictPanel}
 <div ref={stage} className={`graph-stage ${linkFrom?'linking':''}`} tabIndex={0} aria-label="Interactive story canvas. Use Tab to select a card, arrow keys to move it, L to connect it, and Delete to review removal." onPointerDown={(e:any)=>startDrag(e)} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onKeyDown={(e:any)=>{if(e.key==='Escape'){setLinkFrom(null);setSelectedEdge(null);}}}>
 <div className="canvas-world" style={{transform:`translate(${view.x}px, ${view.y}px) scale(${view.scale})`}}><svg className="edge-layer" width="1" height="1" aria-label="Story and image connections"><defs><marker id="edge-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z"/></marker></defs>{edges.map(edge=>{const a=positions[edge.source],b=positions[edge.target];if(!a||!b)return null;const label=edgeLabel(edge);const curve=edgePath(a,b);return <g key={edge.id} className={`graph-edge ${edge.kind} ${selectedEdge?.id===edge.id?'is-selected':''}`}><path d={curve.path} markerEnd="url(#edge-arrow)"/><path d={curve.path} className="edge-hit" onClick={(e:any)=>{e.stopPropagation();setSelectedEdge(edge);}}/><g transform={`translate(${curve.label.x}, ${curve.label.y})`} role="button" tabIndex={0} aria-label={`${label} connection. Select to see options.`} onPointerDown={(e:any)=>e.stopPropagation()} onClick={()=>setSelectedEdge(edge)} onKeyDown={(e:any)=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();setSelectedEdge(edge);}}}><rect x={-Math.max(18,label.length*3.7+8)} y="-12" width={Math.max(36,label.length*7.4+16)} height="24" rx="4"/><text textAnchor="middle" dominantBaseline="central">{edge.kind==='order'?'# ':edge.kind==='assignment'?'↳ ':''}{label}</text></g></g>;})}</svg>
 {visible.map(node=>{const pos=positions[node.id]||{x:0,y:0},type=kindLabel(node);const thumbnail=node.thumbnail_media_id||node.reference_media_ids?.[0];return <article key={node.id} data-node-id={node.id} className={`graph-node ${type} ${selected===node.id||multi.includes(node.id)?'is-selected':''} ${linkFrom===node.id?'link-source':''}`} style={{width:NODE_W,height:NODE_H,transform:`translate(${pos.x}px,${pos.y}px)`}} tabIndex={0} role="button" aria-label={`${type}: ${node.title}. Used ${node.reference_count||0} times.`} aria-pressed={selected===node.id} onPointerDown={(e:any)=>startDrag(e,node)} onPointerMove={move} onPointerUp={end} onClick={(e:any)=>{e.stopPropagation();select(node,e);}} onKeyDown={(e:any)=>key(e,node)}>
 <div className="node-type"><span>{type}</span><span>{node.kind==='asset'?`${node.media_count||0} images`:`${String(node.position+1).padStart(2,'0')}`}</span></div>{thumbnail?<img className="node-image" src={mediaUrl(state.project.id,thumbnail)} alt={`${displayTitle(node.title)} ${node.frame_state?'storyboard image':'reference image'}`} draggable={false}/>:<div className="node-text-preview">{String(node.fields.action||node.fields.summary||node.fields.arc||node.description||'Add a description or story direction')}</div>}<div className="node-content"><h3>{displayTitle(node.title)}</h3><p>{node.kind==='shot'?`${node.fields.framing||'Framing not set'} · ${node.reference_count||0} references`:node.kind==='asset'?`${node.link_count||0} connections · used in ${node.reference_count||0} shots`:`${node.child_count||0} ${node.kind==='sequence'?'scenes':'shots'}`}</p><div className="node-footer">{node.frame_state?<Badge kind={node.frame_state}>{statusLabel(node.frame_state)} image</Badge>:node.tags.slice(0,2).map(t=><span key={t} className="tag">{t}</span>)}{node.child_count!>0&&node.kind!=='asset'&&<button aria-label={`${collapsed.includes(node.id)?'Expand':'Collapse'} ${displayTitle(node.title)}`} onClick={(e:any)=>{e.stopPropagation();setCollapsed(v=>v.includes(node.id)?v.filter(id=>id!==node.id):[...v,node.id]);markDirty();}}>{collapsed.includes(node.id)?'+':'−'}</button>}</div></div></article>;})}</div>
 {!visible.length&&!loading&&<Empty title={mode==='scene'?'Choose a scene to build its board':mode==='assets'?'Build your reference library':'Start your story map'} action={<button onClick={()=>action(mode==='assets'?'asset.create':mode==='scene'?'scene.create':'sequence.create')}>Create a {mode==='assets'?'reference item':mode==='scene'?'scene':'sequence'}</button>}>{mode==='assets'?'Add characters, places, props, and other references here. Their connections will appear as your library grows.':'Create items here or in the story outline. Story order and reference connections will appear as you build.'}</Empty>}
 <div className="canvas-zoom" onPointerDown={(e:any)=>e.stopPropagation()}><button aria-label="Zoom out" onClick={()=>{setView(v=>zoomAt(v,{x:200,y:200},.8));markDirty();}}>−</button><span>{Math.round(view.scale*100)}%</span><button aria-label="Zoom in" onClick={()=>{setView(v=>zoomAt(v,{x:200,y:200},1.25));markDirty();}}>+</button></div>
 </div><div className="canvas-status">{dirty&&<span role="status">Unsaved arrangement · kept while you navigate</span>}<span>{loading?'Loading…':`${visible.length} cards · ${edges.length} connections`}{graph.truncated&&` · ${graph.total} matches; narrow your search to see more (up to 250 cards at a time)`}</span><span>Drag the background to move · Ctrl + scroll to zoom · Arrow keys to arrange · L to connect</span></div>
 {selectedNode&&<div className="selection-tools"><strong>{displayTitle(selectedNode.title)}</strong><button onClick={()=>action(selectedNode.kind+'.update',commandDefaults(selectedNode))}>Edit</button><button onClick={()=>setLinkFrom(selectedNode.id)}>Connect from here</button>{['sequence','scene','shot'].includes(selectedNode.kind)&&<button onClick={()=>action('story.move',commandDefaults(selectedNode))}>Move / reorder</button>}<button onClick={()=>requestDelete(selectedNode.id)}>Remove…</button></div>}
 {selectedEdge&&<div className="selection-tools"><strong>{edgeLabel(selectedEdge)}</strong><span>{selectedEdge.kind==='order'?'Story order':selectedEdge.kind==='assignment'?'Shot reference':selectedEdge.kind==='location_default'?`Location from ${human(selectedEdge.source_scope?.kind||'project').toLowerCase()}`:'Connection between library items'}</span>{selectedEdge.kind==='order'?<button onClick={()=>{const child=state.entities.find(n=>n.id===selectedEdge.target);if(child)action('story.move',commandDefaults(child));}}>Move in story</button>:selectedEdge.kind==='location_default'?<button onClick={()=>{const owner=state.entities.find(n=>n.id===selectedEdge.source);if(owner)action(owner.kind+'.update',commandDefaults(owner));}}>Edit location…</button>:<button onClick={()=>action(selectedEdge.kind==='assignment'?'assignment.remove':'link.remove',{id:selectedEdge.id,revision:selectedEdge.revision})}>Remove connection…</button>}<button onClick={()=>setSelectedEdge(null)}>Close</button></div>}
 {deleteId&&<Modal title="Remove this card?" onClose={closeDelete}><div className="modal-body" data-removal-id={deleteId}><p>Hiding a card removes it from this arrangement. Archiving takes the item out of the active story; deleting removes it permanently.</p>{usage?<div className="usage-summary"><p>{usage.can_delete?'This item is not used elsewhere.':'This item is used in these places:'}</p>{Object.entries(usage).filter(([key,value])=>key!=='can_delete'&&Array.isArray(value)&&value.length>0).length>0&&<ul>{Object.entries(usage).filter(([key,value])=>key!=='can_delete'&&Array.isArray(value)&&value.length>0).map(([key,value]:[string,any])=><li key={key}>{human(key)} · {value.length}</li>)}</ul>}</div>:usageLoading?<p role="status">Checking where this item is used…</p>:usageError?<div className="notice error" role="alert"><strong>We couldn’t check where this item is used.</strong><p>{usageError}</p><button onClick={()=>void refreshUsage(deleteId)}>Retry usage check</button></div>:<p role="status">Usage details are unavailable.</p>}<div className="form-stack"><button onClick={()=>{setHidden([...hidden,deleteId]);markDirty();closeDelete();}}>Hide from this arrangement</button><button disabled={!usage||usageLoading} onClick={()=>{const n=state.entities.find(n=>n.id===deleteId);if(n)action('entity.archive',commandDefaults(n));closeDelete();}}>Archive item…</button><button className="danger" disabled={!usage?.can_delete||usageLoading} onClick={()=>{const n=state.entities.find(n=>n.id===deleteId);if(n)action('entity.delete',commandDefaults(n));closeDelete();}}>Delete item…</button></div></div></Modal>}
 {pendingNavigation&&<Modal title="Unsaved canvas arrangement" onClose={()=>setPendingNavigation(null)}><div className="modal-body"><p>Your Canvas changes have not been saved. Save them to this arrangement, discard them, or stay on this view. Page and project navigation keep your draft. This action replaces the current arrangement, or waits for an active save. The current geometry remains available while you decide.</p>{error&&<ErrorNotice error={error}/>} {conflictPanel}</div><div className="modal-footer"><button onClick={()=>setPendingNavigation(null)}>Stay</button><button onClick={discardAndNavigate} disabled={saving}>Discard changes</button><button className="primary" disabled={!layoutName.trim()||saving||layoutConflict} onClick={()=>void saveAndNavigate()}>{saving?'Saving…':'Save and continue'}</button></div></Modal>}
 </div>;
}
